version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/New_York"
    target-branch: "main"
    reviewers:
      - "@DataBiosphere/broadworkspaces"
    labels:
      - "dependency"
      - "gradle"
    commit-message:
      prefix: "[No Ticket]"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-gradle-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.boot:spring-boot-starter-data-jdbc"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "org.springframework.boot:spring-boot-starter-web"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "org.springframework.boot:spring-boot-starter-test"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
