version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/New_York"
    target-branch: "main"
    reviewers:
      - "@DataBiosphere/broadworkspaces"
    labels:
      - "dependency"
      - "gradle"
    commit-message:
      prefix: "[No Ticket]"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-gradle-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.azure.resourcemanager:azure-resourcemanager-containerinstance"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "com.azure.resourcemanager:azure-resourcemanager-monitor"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "com.azure.resourcemanager:azure-resourcemanager"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "org.springframework.boot-spring-boot-starter-data-jdbc"
        update-types: [ "version-update:semver-patch" ]