# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  db:
    host: jdbc:postgresql://${DATABASE_HOSTNAME:127.0.0.1}:5432
    init: ${INIT_DB:false}
    landingzone:
      name: ${DATABASE_NAME:landingzone_db}
      pass: ${DATABASE_USER_PASSWORD:landingzonepwd}
      user: ${DATABASE_USER:landingzoneuser}
  tracing:
    exportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
  sam:
    basePath: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org}
    resourceId: ${SAM_RESOURCE_ID:landingzone-dev}

# Below here is non-deployment-specific

# When the target is 'local' the write-config.sh script will generate this properties file. It
# contains the configuration of the BPM test application. We can use that application in our
# integration testing to make sure the application code paths are working. However, we do not
# want it to appear in production environments.
spring.config.import: optional:file:../config/local-properties.yml

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mimeTypes: text/css,application/javascript
  port: 8080

spring:
  application.name: landingzonetestharness

landingzone:
  landingzone-database:
    initializeOnStart: ${env.db.init}
    password: ${env.db.landingzone.pass}
    upgradeOnStart: true
    uri: ${env.db.host}/${env.db.landingzone.name}
    username: ${env.db.landingzone.user}

  landingzone-stairway-database:
    initialize-on-start: true
    password: landingzonestairwaypwd
    uri: jdbc:postgresql://127.0.0.1:5432/landingzone_stairway_db
    username: landingzonestairwayuser

  stairway:
    cluster-name-suffix: workspace-stairway
    force-clean-start: false # ${env.db.init}
    max-parallel-flights: 50
    migrate-upgrade: true
    quiet-down-timeout: 30s
    terminate-timeout: 30s
    tracing-enabled: true
    retention-check-interval: 1d
    completed-flight-retention: 7d

  job:
    max-threads: 4
    polling-interval-seconds: 1
    resource-id: mc-terra-workspace-manager
    timeout-seconds: 1800

  protected-data:
    logic-app-resource-id: [PUT VALUE HERE]
    tenant-id: [PUT VALUE HERE]


terra.common:
  kubernetes:
    in-kubernetes: false
