#!/usr/bin/env bash
# execute all of the steps necessary to build the project
set -e #-x

usage() {
  echo "usage: $0 [-h|--help] COMMAND"
  echo ""
  echo "[-h|--help]      print this help text"
  echo ""
  echo "COMMAND is one of the following:"
  echo "- project        the default build command"
  echo "- docker         build a docker image"
  echo "- lint           static file analysis (including formatting)"
  echo "- fixFormat      automatically fix formatting of files"
}

# script variables and defaults
source $(dirname $0)/init.sh


# process command-line options (if any)
die() { log_error "$*" >&2; echo ""; usage; exit 2; }  # complain to STDERR and exit with error
needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }

while getopts h-: OPT; do  # allow -h and -- "with arg"
  # support long options: https://stackoverflow.com/a/28466267/519360
  if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
    OPT="${OPTARG%%=*}"       # extract long option name
    OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
    OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
  fi
  case "$OPT" in
    h | help )     usage; exit 0 ;;
    \? )           usage; exit 2 ;;  # bad short option (error reported via getopts)
    * )            die "Illegal option --$OPT" ;;            # bad long option
  esac
done
shift $((OPTIND-1)) # remove parsed options and args from $@ list


# process positional arguments (if any)
COMMAND=$1
shift 1

# use all trailing arguments as caveats to BUILD command
GRADLE_BUILD_OPTS=${GRADLE_BUILD_OPTS:-"$@"}
log_debug "gradle build opts: ${GRADLE_BUILD_OPTS}"

build_project() {
  cd "${ROOT_DIR}"
  ./gradlew ${GRADLE_OPTS} build ${GRADLE_BUILD_OPTS}
}

build_docker() {
  GIT_REPO_NAME=$(basename "${ROOT_DIR}")
  GIT_SHA_SHORT=$(git rev-parse --short HEAD)

  DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-${GIT_REPO_NAME}}
  DOCKER_IMAGE_NAME_AND_TAG=${DOCKER_IMAGE_NAME_AND_TAG:-"${DOCKER_IMAGE_NAME}:${GIT_SHA_SHORT}"}

  cd "${ROOT_DIR}"
  ./gradlew ${GRADLE_OPTS} :service:jibDockerBuild \
            --image="${DOCKER_IMAGE_NAME_AND_TAG}" \
            -Djib.console=plain

  # the latest tag will allow `docker compose` to work correctly for developers
  if [ -z "$CI" ]; then
    docker image tag "${DOCKER_IMAGE_NAME_AND_TAG}" "${DOCKER_IMAGE_NAME}:latest"
  fi
}

lint() {
  cd "${ROOT_DIR}"
  ./gradlew spotlessCheck
}

fix_format() {
  cd "${ROOT_DIR}"
  ./gradlew spotlessApply
}

case "$COMMAND" in
  project )      build_project ;;
  docker )       build_docker ;;
  lint )         lint ;;
  fixFormat )    fix_format ;;
  * )            die "Missing or invalid positional command: '${COMMAND}'" ;;
esac
