openapi: 3.0.3
info:
  title: Terra Landing Zone Service
  description: |
    Manages landing zones
  version: 0.1.0
paths:
#  /status:
#    get:
#      security: []
#      summary: Returns the operational status of the service.
#      operationId: serviceStatus
#      tags: [ Unauthenticated ]
#      responses:
#        '200':
#          $ref: '#/components/responses/StatusResponse'
#        '500':
#          $ref: '#/components/responses/StatusResponse'

  /version:
    get:
      security: [ ]
      summary: Returns the deployed version of the service.
      operationId: serviceVersion
      tags: [ Unauthenticated ]
      responses:
        '200':
          description: System version response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemVersion'

components:
#  responses:
#    StatusResponse:
#      description: common status response
#      content:
#        application/json:
#          schema:
#            $ref: '#/components/schemas/SystemStatus'

  schemas:
    SystemStatus:
      type: object
      properties:
        ok:
          type: boolean
          description: status of this service
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string
    SystemVersion:
      type: object
      required: [ gitTag, gitHash, github, build ]
      properties:
        gitTag:
          type: string
          description: Git tag of currently deployed app.
        gitHash:
          type: string
          description: Git hash of currently deployed app.
        github:
          type: string
          description: Github link to currently deployed commit.
        build:
          type: string
          description: Version of the currently deployed app declared in build.gradle. Client and server versions are linked.