name: Run linter tests
on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - '**'

jobs:
  lint-and-static-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run linter
      id: run_linter
      run: ./scripts/build checkFormat
